#!/usr/bin/env php
<?php
if(file_exists(__DIR__ . "/vendor")) {
    require_once(__DIR__ . "/vendor/autoload.php");
}elseif(file_exists(__DIR__ . "/../autoload.php")){
    require_once (__DIR__ . "/../autoload.php");
}elseif(file_exists(__DIR__ . "/../../autoload.php")){
    require_once (__DIR__ . "/../../autoload.php");
}else{
    die("Cannot find vendor/autoload.php\n");
}

$environment = array_merge($_SERVER, $_ENV);
ksort($environment);

$cli = new \CloudDoctor\Cli();
$cli->run();
