version: "2.3"

services:
  babysitter:
    image: gone/cloud-doctor
    volumes:
    - ./cloud-definition.yml:/app/cloud-definition.yml:ro
    - ./cloud-definition.override.yml:/app/cloud-definition.override.yml:ro
    - ./cloud-definition.automation-override.yml:/app/cloud-definition.automation-override.yml:rw
    - ./config:/app/config:rw
    - $HOME/.ssh:/root/.ssh:ro


